// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_3._0.Migrations
{
    [DbContext(typeof(Garage_2_0Context))]
    [Migration("20260708120806_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage_3._0.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RegNbr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Arrival = new DateTime(2026, 7, 6, 10, 59, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "Red",
                            Model = "V60",
                            RegNbr = "ABC123",
                            VehicleType = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Arrival = new DateTime(2026, 7, 4, 11, 59, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "Blue",
                            Model = "A50",
                            RegNbr = "BGD567",
                            VehicleType = 1,
                            Wheels = 2
                        },
                        new
                        {
                            Id = 3,
                            Arrival = new DateTime(2026, 6, 5, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Saab",
                            Color = "Yellow",
                            Model = "H88",
                            RegNbr = "KLI908",
                            VehicleType = 2,
                            Wheels = 10
                        },
                        new
                        {
                            Id = 4,
                            Arrival = new DateTime(2026, 7, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "Black",
                            Model = "X76",
                            RegNbr = "TRE654",
                            VehicleType = 1,
                            Wheels = 2
                        },
                        new
                        {
                            Id = 5,
                            Arrival = new DateTime(2026, 7, 1, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Saab",
                            Color = "Blue",
                            Model = "C50",
                            RegNbr = "DUN584",
                            VehicleType = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 6,
                            Arrival = new DateTime(2026, 6, 28, 14, 50, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "White",
                            Model = "BG70",
                            RegNbr = "PLG327",
                            VehicleType = 2,
                            Wheels = 10
                        },
                        new
                        {
                            Id = 7,
                            Arrival = new DateTime(2026, 6, 30, 16, 25, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Mazda",
                            Color = "Black",
                            Model = "BT50",
                            RegNbr = "NJG968",
                            VehicleType = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 8,
                            Arrival = new DateTime(2026, 7, 6, 11, 18, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "White",
                            Model = "A50",
                            RegNbr = "RFM596",
                            VehicleType = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 9,
                            Arrival = new DateTime(2026, 6, 28, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "White",
                            Model = "AZ34",
                            RegNbr = "JYT628",
                            VehicleType = 2,
                            Wheels = 8
                        },
                        new
                        {
                            Id = 10,
                            Arrival = new DateTime(2026, 7, 8, 10, 18, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "Red",
                            Model = "V30",
                            RegNbr = "DER421",
                            VehicleType = 1,
                            Wheels = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
