// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_3._0.Migrations
{
    [DbContext(typeof(Garage_3_0Context))]
    partial class Garage_3_0ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage_3._0.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RegNbr")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VehicleTypes")
                        .HasColumnType("int");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegNbr")
                        .IsUnique();

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Arrival = new DateTime(2026, 7, 6, 10, 59, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "Red",
                            Model = "V60",
                            RegNbr = "ABC123",
                            VehicleTypes = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Arrival = new DateTime(2026, 7, 4, 11, 59, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "Blue",
                            Model = "A50",
                            RegNbr = "BGD567",
                            VehicleTypes = 1,
                            Wheels = 2
                        },
                        new
                        {
                            Id = 3,
                            Arrival = new DateTime(2026, 6, 5, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Saab",
                            Color = "Yellow",
                            Model = "H88",
                            RegNbr = "KLI908",
                            VehicleTypes = 2,
                            Wheels = 10
                        },
                        new
                        {
                            Id = 4,
                            Arrival = new DateTime(2026, 7, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "Black",
                            Model = "X76",
                            RegNbr = "TRE654",
                            VehicleTypes = 1,
                            Wheels = 2
                        },
                        new
                        {
                            Id = 5,
                            Arrival = new DateTime(2026, 7, 1, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Saab",
                            Color = "Blue",
                            Model = "C50",
                            RegNbr = "DUN584",
                            VehicleTypes = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 6,
                            Arrival = new DateTime(2026, 6, 28, 14, 50, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "White",
                            Model = "BG70",
                            RegNbr = "PLG327",
                            VehicleTypes = 2,
                            Wheels = 10
                        },
                        new
                        {
                            Id = 7,
                            Arrival = new DateTime(2026, 6, 30, 16, 25, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Mazda",
                            Color = "Black",
                            Model = "BT50",
                            RegNbr = "NJG968",
                            VehicleTypes = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 8,
                            Arrival = new DateTime(2026, 7, 6, 11, 18, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "White",
                            Model = "A50",
                            RegNbr = "RFM596",
                            VehicleTypes = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 9,
                            Arrival = new DateTime(2026, 6, 28, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "White",
                            Model = "AZ34",
                            RegNbr = "JYT628",
                            VehicleTypes = 2,
                            Wheels = 8
                        },
                        new
                        {
                            Id = 10,
                            Arrival = new DateTime(2026, 7, 8, 10, 18, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Toyota",
                            Color = "Red",
                            Model = "V30",
                            RegNbr = "DER421",
                            VehicleTypes = 1,
                            Wheels = 2
                        });
                });

            modelBuilder.Entity("Garage_3._0.Models.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOutOfService")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOutOfService = false,
                            Location = "",
                            Number = 100
                        },
                        new
                        {
                            Id = 2,
                            IsOutOfService = false,
                            Location = "",
                            Number = 101
                        },
                        new
                        {
                            Id = 3,
                            IsOutOfService = false,
                            Location = "",
                            Number = 102
                        });
                });

            modelBuilder.Entity("Garage_3._0.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumberOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Alfa Romeo",
                            Color = "Blue",
                            Model = "X99",
                            NumberOfWheels = 4,
                            RegistrationNumber = "AAA111",
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Ford",
                            Color = "Blue",
                            Model = "Fiesta",
                            NumberOfWheels = 4,
                            RegistrationNumber = "BBB222",
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Honda",
                            Color = "Red",
                            Model = "CBX750",
                            NumberOfWheels = 2,
                            RegistrationNumber = "CCC333",
                            VehicleTypeId = 3
                        });
                });

            modelBuilder.Entity("Garage_3._0.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bus"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Motorcycle"
                        });
                });

            modelBuilder.Entity("Garage_3._0.Models.Vehicle", b =>
                {
                    b.HasOne("Garage_3._0.Models.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });
#pragma warning restore 612, 618
        }
    }
}
